import {useState} from 'react';

import type {PhysicalDesign,GIKind} from '../../../packages/domain/interventions';
import {INTERVENTION_CATALOG,INTERVENTION_SOURCES,catalogSourceText} from '../../../packages/domain/intervention-catalog';
import {INTERVENTION_NAMES,INTERVENTION_STORIES} from './intervention-style';

type Site={id:string;cells:number[];area_m2:number;slope?:number;parcel_ids?:string[];source_note?:string;protected_reasons?:string[];budgetMinor?:number};
export default function DesignEditor({sites,designs,onChange,disabled,budgetMinor}:{sites:Site[];designs:PhysicalDesign[];onChange:(d:PhysicalDesign[])=>void;disabled:boolean;budgetMinor?:number}){
 const effectiveBudgetMinor=budgetMinor??sites[0]?.budgetMinor??Number.MAX_SAFE_INTEGER;

 const [rating,setRating]=useState<'linear'|'orifice'|'weir'>('linear'),[opening,setOpening]=useState(.01),[width,setWidth]=useState(1),[coefficient,setCoefficient]=useState(.62);
 const [surfaceEnabled,setSurfaceEnabled]=useState(false),[underdrainEnabled,setUnderdrainEnabled]=useState(false),[receiver,setReceiver]=useState(''),[crest,setCrest]=useState(.15),[drainTime,setDrainTime]=useState(60),[flow,setFlow]=useState(1),[percolation,setPercolation]=useState(0),[clogging,setClogging]=useState(0),[slope,setSlope]=useState(1),[axis,setAxis]=useState<'x'|'y'>('x');

 const [site,setSite]=useState(''),[kind,setKind]=useState<GIKind>('rain_garden'),[excavation,setExcavation]=useState(.15),[storage,setStorage]=useState(.15),[conductivity,setConductivity]=useState(20),[assumed,setAssumed]=useState(false),[error,setError]=useState('');
 const [sitePrep,setSitePrep]=useState(2000),[materials,setMaterials]=useState(5000),[installation,setInstallation]=useState(2500),[contingency,setContingency]=useState(500),[maintenance,setMaintenance]=useState(500),[priceYear,setPriceYear]=useState(new Date().getFullYear()),[costBasis,setCostBasis]=useState('User-entered planning allowance; replace with a dated local quote.');

 function chooseKind(next:GIKind){const d=INTERVENTION_CATALOG[next].defaults;setKind(next);setExcavation(d.excavationM);setStorage(d.storageDepthM);setConductivity(d.conductivityMmH);setPercolation(d.percolationMmH);setSlope(d.swaleSlopePercent);setClogging(d.cloggingPercent);}
 function edit(d:PhysicalDesign){setSite(d.id);chooseKind(d.kind);setExcavation(d.excavationM);setStorage(d.storageDepthM);setConductivity(d.conductivityMS*3_600_000);setPercolation(d.percolationMS*3_600_000);setSlope((d.swaleSlope??0)*100);setClogging((d.cloggingFraction??0)*100);setAxis(d.swaleAxis??'x');setAssumed(d.eligibility==='user_assumed');const c=d.costBreakdown;if(c){setSitePrep(c.sitePreparationMinor/100);setMaterials(c.materialsMinor/100);setInstallation(c.installationMinor/100);setContingency(c.contingencyMinor/100);setMaintenance(c.annualMaintenanceMinor/100);setPriceYear(c.priceYear);setCostBasis(c.basis);}else{setSitePrep(0);setMaterials(0);setInstallation(d.costMinor/100);setContingency(0);setMaintenance(0);setCostBasis('Legacy total; replace with itemised dated local quote.');}setError('Editing '+d.id+'; Apply to area saves the replacement.');}

 function add(){const selected=sites.find(s=>s.id===(site||sites[0]?.id));if(!selected)return;if(!assumed){setError('Confirm the exploratory eligibility assumption first.');return;}if(selected.protected_reasons?.length){setError('This candidate is protected: '+selected.protected_reasons.join(', '));return;}if((selected.slope??0)>.1){setError(`Candidate ground slope ${((selected.slope??0)*100).toFixed(1)}% exceeds the 10% screening limit; site grading is not assumed.`);return;}

  const target=sites.find(s=>s.id===receiver)?.cells.find(cell=>!selected.cells.includes(cell));

  if((surfaceEnabled||(underdrainEnabled&&kind!=='detention_basin'))&&receiver!=='external'&&target===undefined){setError('Select a discharge area outside the facility, or an explicit external discharge.');return;}

  if(!Number.isFinite(drainTime)||drainTime<=0){setError('Drainage time must be positive.');return;}

  const control={targetCell:receiver==='external'?null:target!,crestDepthM:crest,ratePerS:1/(drainTime*60),maxFlowM3S:flow/1000};

  const capital=[sitePrep,materials,installation,contingency].reduce((sum,v)=>sum+v,0),costMinor=Math.round(capital*100);
  if([sitePrep,materials,installation,contingency,maintenance].some(v=>!Number.isFinite(v)||v<0)||!Number.isInteger(priceYear)||priceYear<2000||priceYear>2100||!costBasis.trim()){setError('Enter non-negative cost line items, a valid price year and a cost basis.');return;}
  const previous=designs.find(d=>d.id===selected.id),otherCost=designs.filter(d=>d.id!==selected.id&&d.planningConstraint!=='excluded').reduce((sum,d)=>sum+d.costMinor,0);if(otherCost+costMinor>effectiveBudgetMinor){setError(`Budget exceeded: this design would make the selected capital cost $${((otherCost+costMinor)/100).toFixed(2)} against $${(effectiveBudgetMinor/100).toFixed(2)}.`);return;}
  const design:PhysicalDesign={id:selected.id,kind,cells:selected.cells,planningConstraint:previous?.planningConstraint??'optional',eligibility:'user_assumed',excavationM:kind==='permeable_pavement'?0:excavation,storageDepthM:kind==='detention_basin'?0:storage,conductivityMS:conductivity/3_600_000,percolationMS:percolation/3_600_000,cloggingFraction:kind==='permeable_pavement'?clogging/100:0,swaleSlope:kind==='bioswale'?slope/100:0,swaleAxis:axis,surfaceControl:surfaceEnabled?{...control,rating:rating==='linear'?undefined:rating==='orifice'?{kind:'orifice',areaM2:opening,coefficient}:{kind:'weir',widthM:width,coefficient}}:undefined,underdrain:underdrainEnabled&&kind!=='detention_basin'?{...control,crestDepthM:0}:undefined,roughness:INTERVENTION_CATALOG[kind].defaults.roughness,costMinor,costBreakdown:{sitePreparationMinor:Math.round(sitePrep*100),materialsMinor:Math.round(materials*100),installationMinor:Math.round(installation*100),contingencyMinor:Math.round(contingency*100),annualMaintenanceMinor:Math.round(maintenance*100),currency:'USD',priceYear,basis:costBasis.trim()},candidateEvidence:{parcelIds:selected.parcel_ids??[],sourceNote:selected.source_note??'Candidate geometry supplied by the prepared bundle; eligibility unverified.',geometryId:selected.id,protectedReasons:selected.protected_reasons},parameterSource:catalogSourceText(kind)+' Numeric values are user-entered exploratory assumptions.'};

  onChange([...designs.filter(d=>d.id!==design.id),design]);setError('');

 }

 const entry=INTERVENTION_CATALOG[kind];
 return <section className={`design-editor design-${kind}`}><div className="eyebrow">03 / EXPLORATORY DESIGN</div><div className="design-kind-story" aria-live="polite"><span className="design-kind-glyph" aria-hidden="true"><i/><i/><i/></span><div><strong>{INTERVENTION_NAMES[kind]}</strong><p>{INTERVENTION_STORIES[kind]}</p></div></div><fieldset disabled={disabled}><label>Candidate area<select value={site||sites[0]?.id||''} onChange={e=>setSite(e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.id} · {Math.round(s.area_m2)} m²</option>)}</select></label><label>Intervention<select value={kind} onChange={e=>chooseKind(e.target.value as GIKind)}><option value="rain_garden">Rain garden</option><option value="bioswale">Bioswale</option><option value="permeable_pavement">Permeable pavement</option><option value="detention_basin">Detention basin</option></select></label><details className="note"><summary>Parameter sources and limits</summary><p>{entry.note}</p><ul>{entry.sourceIds.map(id=><li key={id}><a href={INTERVENTION_SOURCES[id as keyof typeof INTERVENTION_SOURCES].url} target="_blank" rel="noreferrer">{INTERVENTION_SOURCES[id as keyof typeof INTERVENTION_SOURCES].title}</a></li>)}</ul><p>Displayed ranges are application safety bounds. They do not replace geotechnical, hydraulic, utility or maintenance design.</p></details>

 {kind!=='permeable_pavement'&&<label>Surface depression (m)<input type="number" min={entry.limits.excavationM[0]} max={entry.limits.excavationM[1]} step=".01" value={excavation} onChange={e=>setExcavation(+e.target.value)}/></label>}{kind!=='detention_basin'&&<label>Subsurface water capacity (m)<input type="number" min={entry.limits.storageDepthM[0]} max={entry.limits.storageDepthM[1]} step=".05" value={storage} onChange={e=>setStorage(+e.target.value)}/></label>}<label>Infiltration capacity (mm/h)<input type="number" min={entry.limits.conductivityMmH[0]} max={entry.limits.conductivityMmH[1]} value={conductivity} onChange={e=>setConductivity(+e.target.value)}/></label>{kind==='bioswale'&&<><label>Channel slope (%)<input type="number" min={entry.limits.swaleSlopePercent[0]} max={entry.limits.swaleSlopePercent[1]} step=".1" value={slope} onChange={e=>setSlope(+e.target.value)}/></label><label>Downhill direction<select value={axis} onChange={e=>setAxis(e.target.value as 'x'|'y')}><option value="x">East</option><option value="y">North</option></select></label></>}

 {kind==='permeable_pavement'&&<label>Permeability lost to clogging (%)<input type="number" min="0" max="100" value={clogging} onChange={e=>setClogging(+e.target.value)}/></label>}

 {kind!=='detention_basin'&&<label>Deep percolation (mm/h)<input type="number" min="0" max="3600" value={percolation} onChange={e=>setPercolation(+e.target.value)}/></label>}

 <label><input type="checkbox" checked={surfaceEnabled} onChange={e=>setSurfaceEnabled(e.target.checked)}/> Add a controlled surface outlet / overflow</label>

 {kind!=='detention_basin'&&<label><input type="checkbox" checked={underdrainEnabled} onChange={e=>setUnderdrainEnabled(e.target.checked)}/> Add a subsurface underdrain</label>}

 {(surfaceEnabled||(underdrainEnabled&&kind!=='detention_basin'))&&<>

 <label>Discharge destination<select value={receiver} onChange={e=>setReceiver(e.target.value)}><option value="">Select receiving area</option>{sites.filter(s=>s.id!==(site||sites[0]?.id)).map(s=><option key={s.id} value={s.id}>{s.id} · surface return</option>)}<option value="external">External discharge · leaves model</option></select></label>

 {surfaceEnabled&&<><label>Surface discharge equation<select value={rating} onChange={e=>{const value=e.target.value as typeof rating;setRating(value);setCoefficient(value==='weir'?1.7:.62);}}><option value="linear">Linear storage</option><option value="orifice">Orifice outlet</option><option value="weir">Sharp-crested rectangular spillway</option></select></label>
 {rating==='orifice'&&<label>Total opening area (m²)<input type="number" min=".00001" step=".001" value={opening} onChange={e=>setOpening(+e.target.value)}/></label>}
 {rating==='weir'&&<label>Total spillway width (m)<input type="number" min=".001" step=".1" value={width} onChange={e=>setWidth(+e.target.value)}/></label>}
 {rating!=='linear'&&<label>{rating==='orifice'?'Discharge coefficient (dimensionless)':'Weir coefficient (m½/s)'}<input type="number" min=".01" max={rating==='orifice'?1:4} step=".01" value={coefficient} onChange={e=>setCoefficient(+e.target.value)}/></label>}
 <p className="note">{rating==='orifice'?'Orifice head is measured above the opening centre. Assumes a submerged opening and one-way flow.':rating==='weir'?'Rectangular sharp-crested rating with tailwater reduction. Coefficient is an editable SI assumption.':''}</p>
 <label>{rating==='orifice'?'Opening centre above facility bed (m)':'Surface outlet crest above facility bed (m)'}<input type="number" min="0" step=".05" value={crest} onChange={e=>setCrest(+e.target.value)}/></label></>}

 <label>Storage recession time (minutes)<input type="number" min=".1" step="1" value={drainTime} onChange={e=>setDrainTime(+e.target.value)}/></label>

 <label>Maximum discharge per control (L/s, whole facility)<input type="number" min="0" step=".1" value={flow} onChange={e=>setFlow(+e.target.value)}/></label>

 <p className="note">Nonlinear ratings use a maximum 0.2-second physics step; comparisons can take longer. Control capacity and opening area or width are divided across facility cells; dimensions refer to the whole facility. Surface returns enter one cell in the selected receiving area. Underdrains assume a free outlet; pressure, backflow and pipe sizing are not modelled.</p></>}

 <fieldset><legend>Cost estimate · USD</legend><label>Site preparation<input aria-label="Site preparation cost (USD)" type="number" min="0" step="100" value={sitePrep} onChange={e=>setSitePrep(+e.target.value)}/></label><label>Materials<input aria-label="Materials cost (USD)" type="number" min="0" step="100" value={materials} onChange={e=>setMaterials(+e.target.value)}/></label><label>Installation labour/equipment<input aria-label="Installation cost (USD)" type="number" min="0" step="100" value={installation} onChange={e=>setInstallation(+e.target.value)}/></label><label>Contingency<input aria-label="Contingency cost (USD)" type="number" min="0" step="100" value={contingency} onChange={e=>setContingency(+e.target.value)}/></label><label>Annual maintenance (not in capital budget)<input aria-label="Annual maintenance cost (USD)" type="number" min="0" step="100" value={maintenance} onChange={e=>setMaintenance(+e.target.value)}/></label><label>Price year<input type="number" min="2000" max="2100" value={priceYear} onChange={e=>setPriceYear(+e.target.value)}/></label><label>Cost source / basis<input value={costBasis} onChange={e=>setCostBasis(e.target.value)}/></label><p>Capital total: ${(sitePrep+materials+installation+contingency).toLocaleString()} USD. Enter a dated local quote or estimator reference before decision use.</p></fieldset><label className="check"><input type="checkbox" checked={assumed} onChange={e=>setAssumed(e.target.checked)}/> Assume this site is eligible for this exploratory run.</label><p className="note">Parameters and cost are editable assumptions. Surface overtopping follows terrain; full storage leaves excess water on the surface. Discharge controls are explicit assumptions, not engineered outlet sizing. Parcel eligibility remains unverified.</p><button className="primary" onClick={add} disabled={!sites.length}>Apply to area</button>{error&&<p className="error">{error}</p>}{designs.map(d=><div className="design-row" key={d.id}><span>{d.kind.replaceAll('_',' ')} · {d.id}</span><select aria-label={'Planning constraint for '+d.id} value={d.planningConstraint??'optional'} onChange={e=>onChange(designs.map(x=>x.id===d.id?{...x,planningConstraint:e.target.value as PhysicalDesign['planningConstraint']}:x))}><option value="optional">Planner may choose</option><option value="locked">Required in plan</option><option value="excluded">Exclude from plan</option></select><button onClick={()=>edit(d)}>Edit</button><button onClick={()=>onChange(designs.filter(x=>x.id!==d.id))}>Remove</button></div>)}</fieldset></section>;

}
