import type {CoastalBoundary} from '../../../packages/simulation/src/coastal';
import {inputIdentity} from '../../../packages/simulation/src/identity';
import {useState,useEffect} from 'react';
import {validateGPUInput,type GPUInput,type Inflow,type Outlet} from '../../../packages/simulation/src/gpu';
import {forcingComponents,type FloodConfiguration} from '../../../packages/domain/scenario';
export type {FloodConfiguration} from '../../../packages/domain/scenario';
export default function FloodInputs({input,value,onChange,disabled,elevationOriginM,verticalDatum}:{elevationOriginM?:number;verticalDatum?:string;input:GPUInput|null;value:FloodConfiguration;onChange:(v:FloodConfiguration)=>void;disabled:boolean}){
 const components=forcingComponents(value);
 const [seaStart,setSeaStart]=useState(0),[seaPeak,setSeaPeak]=useState(2),[seaRise,setSeaRise]=useState(600),[seaDatum,setSeaDatum]=useState(''),[seaAssumed,setSeaAssumed]=useState(false);
 const [coastEdge,setCoastEdge]=useState('north');
 const [edge,setEdge]=useState('north'),[flow,setFlow]=useState(1),[duration,setDuration]=useState(600),[source,setSource]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const b=value.coastal;if(!b)return;setCoastEdge(b.edge);setSeaStart(b.levels[0].elevationM);setSeaPeak(b.levels[1]?.elevationM??b.levels[0].elevationM);setSeaRise(b.levels[1]?.timeS??600);setSeaDatum(b.datum);setSource(b.source);setSeaAssumed(true);},[value.coastal]);
 function applyCoast(){try{if(!input)return;if(!seaAssumed)throw new Error('Acknowledge the exploratory coastal assumptions first.');
 const cells=Array.from({length:input.z.length},(_,i)=>i).filter(i=>input.planningWaterMask?.[i]&&!input.solid[i]&&(coastEdge==='north'?Math.floor(i/input.nx)===input.ny-1:coastEdge==='south'?i<input.nx:coastEdge==='west'?i%input.nx===0:i%input.nx===input.nx-1));
 const coastal:CoastalBoundary={edge:coastEdge as CoastalBoundary['edge'],cells,levels:[{timeS:0,elevationM:seaStart},{timeS:seaRise,elevationM:seaPeak},{timeS:2*seaRise,elevationM:seaStart}],source,datum:seaDatum,segment_ids:[`grid-${coastEdge}-edge`],source_kind:'assumed',source_epoch:'unknown',vertical_transform:'unverified',coverage_start_s:0,coverage_end_s:2*seaRise,bathymetry_status:'missing',channel_support_status:'missing'};
 validateGPUInput({...input,coastal});onChange({...value,coastal,source});setError('');}catch(e){setError(String(e));}}
 function applyEdge(){try{if(!input)return;if(!source.trim())throw new Error('Enter a source or explicitly describe the assumption.');const cells=Array.from({length:input.z.length},(_,i)=>i).filter(i=>!input.solid[i]&&(edge==='north'?Math.floor(i/input.nx)===input.ny-1:edge==='south'?i<input.nx:edge==='west'?i%input.nx===0:i%input.nx===input.nx-1));if(!cells.length)throw new Error('Selected edge has no exposed cells');
  const inflows=cells.map(cell=>({cell,flowM3S:flow/cells.length,startS:0,endS:duration,source}));validateGPUInput({...input,inflows,outlets:value.outlets});onChange({...value,inflows,source});setError('');
 }catch(e){setError(String(e));}}
 async function importDrainage(file:File){try{if(!input)return;if(file.size>1000000)throw new Error('Configuration exceeds 1 MB');const config=JSON.parse(await file.text());if(config.inputHash!==await inputIdentity(input))throw new Error('Configuration must match this grid and terrain checksum');if(!Array.isArray(config.outlets)||!config.source?.trim())throw new Error('Provide outlets and source');validateGPUInput({...input,outlets:config.outlets});onChange({...value,outlets:config.outlets,source:config.source});setError('');}catch(e){setError(String(e));}}
 async function template(){if(!input)return;const data={inputHash:await inputIdentity(input),source:'REPLACE with parameter provenance',outlets:[],outletSchema:{cell:'zero-based row-major non-building cell',crestDepthM:'metres above local terrain',ratePerS:'linear reservoir coefficient, 1/s',maxFlowM3S:'external export capacity, m3/s',tailwaterElevationM:'optional downstream water elevation in the local model vertical datum',source:'measurement or explicit assumption'}};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='sponge-drainage-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section><div className="eyebrow">FLOOD SOURCES & DRAINAGE</div><fieldset disabled={disabled||!input}><label>Flood scenario<select value={value.mode} onChange={e=>onChange({...value,mode:e.target.value as FloodConfiguration['mode'],components:value.components??{rainfall:true,external:false,coastal:true}})}><option value="rain">Rainfall flooding</option><option value="external">External inflow only</option><option value="compound">Rainfall + external inflow</option><option value="coastal">Exploratory coastal water level</option><option value="combined">Combined flood sources</option></select></label>
 {value.mode==='combined'&&<div className="note"><p>Choose sources that act together. Each uses its own timing; coastal levels hold their final value after the series ends. These combinations are exploratory.</p>{(['rainfall','external','coastal'] as const).map(key=><label key={key}><input type="checkbox" checked={components[key]} onChange={e=>onChange({...value,components:{...components,[key]:e.target.checked}})}/>{key==='rainfall'?'Include rainfall':key==='external'?'Include external inflow':'Include coastal water level'}</label>)}</div>}
 {components.external&&<><label>Inflow edge<select value={edge} onChange={e=>setEdge(e.target.value)}>{['north','south','east','west'].map(x=><option key={x}>{x}</option>)}</select></label><label>Total inflow (m³/s)<input type="number" min="0" step=".1" value={flow} onChange={e=>setFlow(+e.target.value)}/></label><label>Inflow duration (seconds)<input type="number" min="1" value={duration} onChange={e=>setDuration(+e.target.value)}/></label><label>Source or assumption<input value={source} onChange={e=>setSource(e.target.value)} placeholder="Describe this exploratory inflow"/></label><button onClick={applyEdge}>Apply inflow</button><p className="note">{value.inflows.length} configured inflow cells. Total discharge is spread equally across exposed edge cells, with zero imposed momentum. This is a prescribed surface source, not a river-channel or coastal-wave model.</p></>}
 {components.coastal&&<><p className="note">Prescribed coastal reservoir level: water can enter and leave the selected boundary. Existing terrain is not verified seabed data. This is not a validated storm-surge or tsunami model.</p><p className="note">Terrain reference: {verticalDatum??'unspecified'}. {Number.isFinite(elevationOriginM)?'Local water elevation = source-datum elevation minus '+elevationOriginM+' m. This arithmetic does not resolve a datum mismatch.':'Terrain offset unavailable: verify alignment before using source water levels.'}</p><label>Coastal edge<select value={coastEdge} onChange={e=>setCoastEdge(e.target.value)}>{['north','south','east','west'].map(x=><option key={x}>{x}</option>)}</select></label><label>Initial water elevation (local model metres)<input type="number" value={seaStart} onChange={e=>setSeaStart(+e.target.value)}/></label><label>Peak water elevation (local model metres)<input type="number" value={seaPeak} onChange={e=>setSeaPeak(+e.target.value)}/></label><label>Rise time (seconds)<input type="number" min="1" value={seaRise} onChange={e=>setSeaRise(+e.target.value)}/></label><label>Vertical datum and terrain alignment<input value={seaDatum} onChange={e=>setSeaDatum(e.target.value)} placeholder="Explain how water levels align with local terrain"/></label><label>Coastal source or assumption<input value={source} onChange={e=>setSource(e.target.value)}/></label><label><input type="checkbox" checked={seaAssumed} onChange={e=>setSeaAssumed(e.target.checked)}/>I am using explicit exploratory terrain and water-level assumptions.</label><button onClick={applyCoast}>Apply coastal boundary</button><p className="note">{value.coastal?.cells.length??0} configured boundary cells. Level returns to its initial value after twice the rise time, then remains there. Only mapped-water boundary cells are eligible.</p></>}
 <p className="note">{value.outlets.length} active parameterised outlets. Downstream head can limit drainage; reverse flow and sewer routing are not modelled.</p><button onClick={template}>Download drainage template</button><label>Import sourced drainage parameters<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void importDrainage(file);e.target.value='';}}/></label><button onClick={()=>onChange({...value,outlets:[]})}>Clear outlets</button>{error&&<p className="error" role="alert">{error}</p>}
 </fieldset></section>;
}
