"""Local planning currency lookup from ISO 3166-1 alpha-2 country codes.

The lookup deliberately returns only the currency code. Exchange rates are not
part of terrain preparation, so user-entered planning amounts are never
silently converted.
"""
from __future__ import annotations

_GROUPS = {
    "AED": "AE",
    "AFN": "AF",
    "ALL": "AL",
    "AMD": "AM",
    "ANG": "CW SX",
    "AOA": "AO",
    "ARS": "AR",
    "AUD": "AU CC CX HM KI NR NF TV",
    "AWG": "AW",
    "AZN": "AZ",
    "BAM": "BA",
    "BBD": "BB",
    "BDT": "BD",
    "BHD": "BH",
    "BIF": "BI",
    "BMD": "BM",
    "BND": "BN",
    "BOB": "BO",
    "BRL": "BR",
    "BSD": "BS",
    "BTN": "BT",
    "BWP": "BW",
    "BYN": "BY",
    "BZD": "BZ",
    "CAD": "CA",
    "CDF": "CD",
    "CHF": "CH LI",
    "CLP": "CL",
    "CNY": "CN",
    "COP": "CO",
    "CRC": "CR",
    "CUP": "CU",
    "CVE": "CV",
    "CZK": "CZ",
    "DJF": "DJ",
    "DKK": "DK FO GL",
    "DOP": "DO",
    "DZD": "DZ",
    "EGP": "EG",
    "ERN": "ER",
    "ETB": "ET",
    "EUR": "AD AT AX BE BL BG CY DE EE ES FI FR GF GP GR HR IE IT LT LU LV MC ME MF MQ MT NL PM PT RE SI SK SM TF VA XK",
    "FJD": "FJ",
    "FKP": "FK",
    "GBP": "GB GG IM JE",
    "GEL": "GE",
    "GHS": "GH",
    "GIP": "GI",
    "GMD": "GM",
    "GNF": "GN",
    "GTQ": "GT",
    "GYD": "GY",
    "HKD": "HK",
    "HNL": "HN",
    "HTG": "HT",
    "HUF": "HU",
    "IDR": "ID",
    "ILS": "IL PS",
    "INR": "IN",
    "IQD": "IQ",
    "IRR": "IR",
    "ISK": "IS",
    "JMD": "JM",
    "JOD": "JO",
    "JPY": "JP",
    "KES": "KE",
    "KGS": "KG",
    "KHR": "KH",
    "KMF": "KM",
    "KPW": "KP",
    "KRW": "KR",
    "KWD": "KW",
    "KYD": "KY",
    "KZT": "KZ",
    "LAK": "LA",
    "LBP": "LB",
    "LKR": "LK",
    "LRD": "LR",
    "LSL": "LS",
    "LYD": "LY",
    "MAD": "MA EH",
    "MDL": "MD",
    "MGA": "MG",
    "MKD": "MK",
    "MMK": "MM",
    "MNT": "MN",
    "MOP": "MO",
    "MRU": "MR",
    "MUR": "MU",
    "MVR": "MV",
    "MWK": "MW",
    "MXN": "MX",
    "MYR": "MY",
    "MZN": "MZ",
    "NAD": "NA",
    "NGN": "NG",
    "NIO": "NI",
    "NOK": "BV NO SJ",
    "NPR": "NP",
    "NZD": "CK NU NZ PN TK",
    "OMR": "OM",
    "PAB": "PA",
    "PEN": "PE",
    "PGK": "PG",
    "PHP": "PH",
    "PKR": "PK",
    "PLN": "PL",
    "PYG": "PY",
    "QAR": "QA",
    "RON": "RO",
    "RSD": "RS",
    "RUB": "RU",
    "RWF": "RW",
    "SAR": "SA",
    "SBD": "SB",
    "SCR": "SC",
    "SDG": "SD",
    "SEK": "SE",
    "SGD": "SG",
    "SHP": "AC SH TA",
    "SLE": "SL",
    "SOS": "SO",
    "SRD": "SR",
    "SSP": "SS",
    "STN": "ST",
    "SYP": "SY",
    "SZL": "SZ",
    "THB": "TH",
    "TJS": "TJ",
    "TMT": "TM",
    "TND": "TN",
    "TOP": "TO",
    "TRY": "TR",
    "TTD": "TT",
    "TWD": "TW",
    "TZS": "TZ",
    "UAH": "UA",
    "UGX": "UG",
    "USD": "AS BQ EC FM GU IO MH MP PR PW SV TC TL UM US VG VI",
    "UYU": "UY",
    "UZS": "UZ",
    "VES": "VE",
    "VND": "VN",
    "VUV": "VU",
    "WST": "WS",
    "XAF": "CF CG CM GA GQ TD",
    "XCD": "AG AI DM GD KN LC MS VC",
    "XOF": "BF BJ CI GW ML NE SN TG",
    "XPF": "NC PF WF",
    "YER": "YE",
    "ZAR": "ZA",
    "ZMW": "ZM",
    "ZWG": "ZW",
}

CURRENCY_BY_COUNTRY = {
    country: currency for currency, countries in _GROUPS.items() for country in countries.split()
}


def currency_for_country(country_code: str | None) -> str | None:
    """Return the territory's planning currency, or None when it is unknown."""
    if not isinstance(country_code, str):
        return None
    return CURRENCY_BY_COUNTRY.get(country_code.strip().upper())
