"""Present numerical candidate evidence without implying flood accuracy or adoption."""
import json
from pathlib import Path

root=Path('artifacts/validation');verification=Path('artifacts/verification')
tail=json.loads((verification/'sandy-positivity-tail-v1.json').read_text())
references=[json.loads((verification/f'positivity-coastal-reference-{mode}-v1.json').read_text()) for mode in ('nvidia','software')]
peak=max(r['max_peak_error_m'] for ref in references for r in ref['results'])
accuracy_path=root/'sandy-2012-positivity-v1/accuracy.json'
accuracy_note=''
if accuracy_path.exists():
    a=json.loads(accuracy_path.read_text())['runs'][0]
    accuracy_note=f'<h2>Sandy flood-height assessment</h2><p>The separate candidate run compares {a["compared_count"]} of {a["total_count"]} retained marks, with {a["missed_flood_count"]} dry misses. Wet-point RMSE is {a["rmse_m"]:.4f} m; the supplied gauge peak transferred to those same wet marks gives {a["gauge_only_baseline"]["rmse_m"]:.4f} m. Two building-cell marks remain unresolved. This does not demonstrate a meaningful flood-height improvement over that simple reference. It does not validate city-wide extent or timing, and it does not reinstate the rejected original replay.</p><p><a href="sandy-2012-positivity-v1/accuracy.json">Candidate point assessment and exclusions</a></p>'
doc=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SPONGE numerical positivity candidate</title>
<style>body{{font:16px/1.6 system-ui;background:#f5f4ee;color:#183c42;margin:0}}main{{max-width:1050px;margin:auto;padding:28px}}article{{padding:20px;background:white;border:1px solid #cad6d0;margin:18px 0}}.notice{{background:#fff0d7;padding:18px;border-left:4px solid #b97828}}a{{color:#006b85}}progress{{width:100%}}</style>
<main><h1>Numerical fix: explicitly account for tiny negative-depth roundoff</h1>
<p class="notice">Experimental candidate only. Production defaults and the original rejected Sandy replay remain unchanged. A numerical fix does not establish better real-world flood accuracy.</p>
<p>The candidate corrects depths only between Ã¢Ë†â€™1eÃ¢Ë†â€™10 m and zero, records the added volume, and rejects larger negatives or excess cumulative correction. The ordinary physical mass residual remains visible. Versioned checkpoints retain correction accounting and retries restore it.</p>
<h2>Completed evidence</h2><ul><li>Sandy's final nine simulated minutes: original keeps one negative cell; candidate has none. Maximum peak-depth difference: {tail['comparison']['maxPeakDepthDifferenceM']} m. Correction: {tail['migration']['volumeM3']:.3e} mÃ‚Â³. Candidate checkpoint restores exactly.</li>
<li>Five coastal reference cases pass on NVIDIA and five on the software renderer. Largest peak-depth error against the float64 reference: {peak:.3e} m. These cases test shared numerical assumptions, not observed flood accuracy.</li>
<li>Focused tests cover correction accounting, material-negative rejection, immutable original checkpoints, exact continuation, and rollback after a later failed timestep stage.</li></ul>
<p><a href="../verification/sandy-positivity-tail-v1.json">Sandy continuation evidence</a> Ã‚Â· <a href="../verification/positivity-coastal-reference-nvidia-v1.json">NVIDIA reference cases</a> Ã‚Â· <a href="../verification/positivity-coastal-reference-software-v1.json">Software reference cases</a></p>
{accuracy_note}<h2>Full-event regressions</h2><p>Same grid, terrain, buildings and forcing as each original. Sandy runs first, then Matthew. Acceptance requires a complete nonnegative replay, passing water accounting and no more than 0.0001 m change in any saved depth or peak. Where an accepted original point assessment exists, retain its regression checks. Original Sandy has no accepted accuracy score.</p>
<div id="jobs"></div><h2>Sandy full-event diagnosis</h2><p>The complete candidate replay passes nonnegative-depth and water-accounting checks, but fails the frozen change gate: 0.00010705 m maximum saved-depth difference exceeds 0.00010000 m. Exactly one snapshot exceeds the limit. Peak differences stay below it. This is a retained engineering failure, not a measured loss of real-world flood accuracy.</p><img src="sandy-2012-positivity-v1/divergence-diagnosis.png" alt="Saved depth and peak differences with the frozen threshold and cumulative roundoff correction" style="max-width:100%"><p><a href="sandy-2012-positivity-v1/divergence-diagnosis.json">Exact divergent frame and checksums</a></p><h2>Next accuracy diagnostic</h2><p><a href="matthew-2016-domain4km/experiment-report.html">Larger-domain test at the same cell spacing</a>: preserve the complete old core and move outer edges farther away. <a href="positivity-decision.json">Completed numerical candidate decision</a>.</p><h2>Next untouched event</h2><p>Dorian 2019 in Hatteras is provisionally available, but boundary geometry and the building-corner observation need review before any simulation or measured-height exposure. Its 2018 terrain compilation covers the proposed domain; below-datum terrain intersects all four edges. A one-edge reservoir with three walls must not be presumed suitable.</p>
<p><a href="dorian-2019/preflight.html">Dorian metadata and terrain preflight</a> Ã‚Â· <a href="matthew-2016/error-diagnosis.html">Matthew accuracy diagnosis</a> Ã‚Â· <a href="index.html">All historical comparisons</a></p></main>
<script>
const configs=[['sandy-2012-positivity-v1','Sandy 2012 Ã‚Â· 128-grid',18],['matthew-2016-positivity-v1','Matthew 2016 Ã‚Â· 64-grid',24]];
const element=(tag,text)=>{{const el=document.createElement(tag);el.textContent=text??'';return el}};
async function read(path){{const r=await fetch(path+'?v='+Date.now(),{{cache:'no-store'}});if(!r.ok||r.headers.get('content-type')?.includes('text/html'))return null;return r.json();}}
for(const [directory,title,hours] of configs){{const card=element('article'),heading=element('h3',title),status=element('p','Queued'),bar=element('progress'),detail=element('p'),links=element('p');bar.max=hours;bar.value=0;card.append(heading,status,bar,detail,links);document.getElementById('jobs').append(card);
async function refresh(){{try{{const [job,p,result]=await Promise.all([read(directory+'/job-status.json'),read(directory+'/progress.json'),read(directory+'/candidate-comparison.json')]);status.textContent=job?'Local job: '+job.stage:'Queued after Sandy';if(p){{bar.value=p.simulatedHours;detail.textContent=p.simulatedHours.toFixed(2)+' / '+hours+' simulated hours';}}if(result){{bar.value=hours;status.textContent=result.candidate_numerical_regression_passed?'Passes this numerical regression; still experimental':'Fails this numerical regression';detail.textContent='Maximum saved depth difference: '+result.max_saved_depth_difference_m.toExponential(3)+' m; peak difference: '+result.max_saved_peak_difference_m.toExponential(3)+' m; frozen limit: 1.000e-4 m; correction: '+result.final_roundoff_correction_m3.toExponential(3)+' mÃ‚Â³';const a=element('a','Full comparison');a.href=directory+'/candidate-comparison.json';links.replaceChildren(a);}}if(job?.error)status.textContent+=' Ã‚Â· '+job.error;}}catch{{status.textContent='Evidence unavailable; no pass inferred';}}}}refresh();setInterval(refresh,10000);}}
</script></html>'''
(root/'positivity-report.html').write_text(doc,encoding='utf-8');print(root/'positivity-report.html')
