"""Expose the fresh-event outcome and its preserved exclusions in one report."""
import html
import json
import sys
from pathlib import Path

root=Path(sys.argv[1]);p=json.loads((root/'protocol.json').read_text());path=root/'holdout-comparison.json'
ready=path.exists();fmt=lambda v:'Unavailable' if v is None else f'{v:.4f}'
body='''<p class="notice"><strong>Simulations running; flood-height accuracy has not been scored.</strong> Preflight found that outdoor mark 16723 is usable at 64 cells but overlaps a building cell at 128. This coverage regression is retained. The observation and domain will not be moved to improve the score.</p><p id="progress">Checking local computation…</p><p id="partial-audit"></p><img src="input-geometry.png" alt="Frozen terrain, building cells and supported or unresolved observation locations">'''
if ready:
    r=json.loads(path.read_text());g=r['regression'];old,new=r['individual_observations'];lookup={s['observation_id']:s for s in new['samples']}
    rows=''.join('<tr>'+''.join('<td>'+html.escape(str(v))+'</td>' for v in (a['observation_id'],a['quality_description'],fmt(a['observed_elevation_m']),a['status'],fmt(a.get('error_m')),lookup[a['observation_id']]['status'],fmt(lookup[a['observation_id']].get('error_m'))))+'</tr>' for a in old['samples'])
    verdict='Refinement fails this new event’s regression checks' if not g['regression_gate_passed'] else 'Refinement passes this event’s screening checks'
    body=f'''<p class="notice"><strong>{verdict}.</strong> General flood accuracy remains unvalidated. No production default has changed.</p>
<p>Common-point RMSE: {fmt(g['baseline_common_rmse_m'])} → {fmt(g['candidate_common_rmse_m'])} m. Dry misses: {g['dry_before']} → {g['dry_after']}. Lost supported observations: {html.escape(str(g['lost_supported_ids']))}.</p>
<div class="scroll"><table><thead><tr><th>USGS mark</th><th>Source quality</th><th>Observed NAVD88 m</th><th>64 status</th><th>64 error m</th><th>128 status</th><th>128 error m</th></tr></thead><tbody>{rows}</tbody></table></div><img src="grid-comparison.png" alt="Both grids with unchanged surveyed observation coordinates">'''
    for run in r['quality_and_spatial_strata']:
        s=run['all'];q=run['good_or_excellent']
        body+=f'''<h2>{run['grid_cells']} × {run['grid_cells']}</h2><p>All wet comparable marks: {len(s['wet_ids'])}; RMSE {fmt(s['rmse_m'])} m; MAE {fmt(s['mae_m'])} m; bias {fmt(s['bias_m'])} m; worst absolute error {fmt(s['worst_absolute_error_m'])} m. Gauge-only RMSE on those same marks: {fmt(s['same_wet_gauge_rmse_m'])} m.</p><p>Good/excellent-quality comparable marks: {len(q['wet_ids'])}; RMSE {fmt(q['rmse_m'])} m. Quality categories are kept separate; missing comparisons are not zero error.</p>'''
    body+='<p><a href="inspection.html">Play both computed replays and inspect every mark</a> · <a href="holdout-comparison.json">Full results, quality and spatial groups</a></p>'
    if (root/'error-diagnosis.html').exists():
        body+='<p><a href="error-diagnosis.html">Why did the finer grid worsen? Terrain access and water-level diagnostics</a></p>'
doc=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Matthew 2016 new-event test</title><style>body{{font:16px/1.6 system-ui;background:#f5f4ee;color:#183c42;margin:0}}main{{max-width:1150px;margin:auto;padding:28px}}.notice{{background:#fff0d7;padding:18px;border-left:4px solid #b97828}}img{{max-width:100%;margin:16px 0}}table{{border-collapse:collapse;font-size:14px}}td,th{{padding:10px;border-bottom:1px solid #ccd5d0;text-align:left}}.scroll{{overflow:auto}}a{{color:#006b85}}</style><main>
<h1>New comparison: Matthew 2016, Charleston</h1><p>Frozen before measured high-water elevations were inspected. Same 2 km domain, source terrain, footprints, forcing and model parameters at 64 and 128 cells.</p>{body}
<h2>What this test can establish</h2><p>Four outdoor marks are retained, with three nearby poor-quality lawn/shrub records and one farther-away good-quality stairs record. The aquarium mark has no stated vertical datum and remains unresolved. Low error on only the nearby poor-quality marks cannot replace the missing good-quality comparison.</p>
<h2>Geometry conflict found before scoring</h2><p>The stairs observation coordinate falls inside the current footprint polygon. The coarse cell centre lies outside that polygon, while the fine cell centre lies inside it. The source lists Phone/Car GPS for horizontal position; good HWM quality does not establish precise coordinates. This is a conflict among survey position, an outdoor description and current geometry. The prescribed coverage gate is retained, but its failure alone cannot establish that finer-grid hydraulics are less accurate.</p><img src="building-overlap-diagnosis.png" alt="Same surveyed coordinate and source footprint with different 64 and 128 cell-centre classifications"><p><a href="building-overlap-diagnosis.json">Geometry evidence</a></p>
<p>The source terrain was compiled in 2019, after the storm; buildings are current. Gauge forcing is transferred spatially. Waves, wind, rainfall and drainage are omitted. There is no independent dry-area mask or arrival-time record here, so city-wide extent and timing accuracy remain untested.</p>
<p><a href="evaluation-plan.json">Frozen evaluation criteria</a> · <a href="protocol.json">Frozen inputs</a> · <a href="../index.html">All historical comparisons</a></p></main>
<script>const ready={str(ready).lower()};let lastProgress=null,lastChanged=Date.now();async function read(name,optional=false){{const r=await fetch(name+'?v='+Date.now(),{{cache:'no-store'}});if(optional&&(!r.ok||r.headers.get('content-type')?.includes('text/html')))return null;if(!r.ok)throw Error(name);return r.json();}}
async function refresh(){{if(ready)return;try{{const [j,h]=await Promise.all([read('job-status.json'),read('holdout-status.json',true)]);const e=document.getElementById('progress');e.textContent='Local computation: '+j.stage;if(h?.stage==='completed'){{location.reload();return;}}if(h?.stage==='failed'){{e.textContent='Comparison workflow failed: '+h.error+'; saved evidence is retained.';return;}}if(j.stage==='simulating'){{const p=await read('progress.json');const key=p.grid+':'+p.simulatedHours;if(key!==lastProgress){{lastProgress=key;lastChanged=Date.now();}}e.textContent+=' · '+p.grid+' × '+p.grid+' · '+p.simulatedHours.toFixed(2)+' / 24 simulated hours'+(p.grid===64?' · run 1 of 2; 128-grid queued':' · run 2 of 2; 64-grid complete')+(Date.now()-lastChanged>60000?' · progress unchanged for over one minute':'');const a=await read('checkpoint-audit-'+p.grid+'.json',true);if(a)document.getElementById('partial-audit').textContent='Partial checkpoint audit through '+a.simulated_hours.toFixed(2)+' simulated hours: depth-volume '+(a.depth_volume_crosscheck_passed?'passed':'failed')+'; mass gate '+(a.mass_gate_passed?'passed':'failed')+'. This checks saved numerical state, not flood accuracy.';}}else if(j.stage==='completed'){{e.textContent='Both simulations complete; '+(h?.stage??'awaiting comparison');}}if(j.error)e.textContent+=' · '+j.error;}}catch{{document.getElementById('progress').textContent='Live status unavailable; no completion inferred.';}}}}refresh();setInterval(refresh,10000);</script></html>'''
(root/'holdout-report.html').write_text(doc,encoding='utf-8');print('Rendered',root/'holdout-report.html')
