import registry from '../contracts/engine-capabilities.json';
import type {ScenarioSpecV2} from '../contracts/src/ScenarioSpecV2';
import type {GPUInput} from '../simulation/src/gpu';
import type {ScenarioForcingV2} from './scenario';
import generatedValidateShape from './generated/scenario-validator';

type ShapeValidator=((value:unknown)=>value is ScenarioSpecV2)&{errors?:{instancePath:string;message?:string}[]|null};
// Generated by scripts/generate-scenario-validator.mjs. Ajv's normal runtime
// compiler uses new Function(), which a strict production CSP must reject.
const validateShape=generatedValidateShape as ShapeValidator;
/** Wire optional nulls and omitted fields are equivalent; object order is not physical. */
export function sameScenarioValue(a:unknown,b:unknown):boolean{
 const normalize=(v:any):any=>Array.isArray(v)?v.map(normalize):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().filter(k=>v[k]!=null).map(k=>[k,normalize(v[k])])):v;
 return JSON.stringify(normalize(a))===JSON.stringify(normalize(b));
}
export function parseScenarioSpec(value:unknown):ScenarioSpecV2{
 if(!validateShape(value))throw new Error('Invalid scenario contract: '+JSON.stringify(validateShape.errors?.map(e=>({path:e.instancePath,message:e.message}))));
 const spec=value as ScenarioSpecV2,f=spec.forcing,d=spec.domain,c=f.components,s=f.storm;
 if(!c.rainfall&&!c.external&&!c.coastal)throw new Error('Enable at least one flood source');
 if(c.coastal!==!!f.coastal||c.external!==!!f.inflows.length)throw new Error('Enabled components must match supplied sources');
 if(!c.rainfall&&(s.depth!==0||s.intervals!=null))throw new Error('Disabled rainfall contains forcing');
 let end=0,depth=0;
 for(const i of s.intervals??[]){
  if(i.start_s<end||i.end_s<=i.start_s||i.end_s>s.duration)throw new Error('Invalid rainfall interval order or duration');
  end=i.end_s;depth+=(i.end_s-i.start_s)*i.rate_m_s;
 }
 if(s.intervals!=null&&Math.abs(depth-s.depth)>Math.max(1e-9,s.depth*1e-4))throw new Error('Rainfall integral does not match event depth');
 const n=d.nx*d.ny,finish=s.duration+s.recession;
 for(const rows of [f.inflows,f.outlets]){
  const cells=rows.map(i=>i.cell);
  if(cells.some(i=>i>=n)||new Set(cells).size!==cells.length)throw new Error('Invalid or duplicate source cells');
 }
 for(const i of f.inflows)if(i.endS<=i.startS||i.endS>finish)throw new Error('Inflow exceeds simulation window');
 if(f.coastal){
  const b=f.coastal;
  if(new Set(b.cells).size!==b.cells.length)throw new Error('Duplicate coastal cells');
  for(const i of b.cells){const x=i%d.nx,y=Math.floor(i/d.nx);if(i<0||i>=n||!{west:x===0,east:x===d.nx-1,south:y===0,north:y===d.ny-1}[b.edge])throw new Error('Invalid coastal boundary cell');}
  if(b.levels[0].timeS!==0||b.levels.some((v,i)=>i>0&&v.timeS<=b.levels[i-1].timeS))throw new Error('Invalid coastal level series');
  if(b.levels.at(-1)!.timeS>finish)throw new Error('Coastal series exceeds simulation window');
  if(f.inflows.some(i=>b.cells.includes(i.cell)))throw new Error('External inflow overlaps coastal boundary');
 }
 return spec;
}

export function assessScenario(spec:ScenarioSpecV2){
 parseScenarioSpec(spec);
 const c=spec.forcing.components,requested=new Set(spec.required_capabilities);
 if(c.rainfall)requested.add('rainfall');
 if(c.external)requested.add('external_inflow');
 if(c.coastal)requested.add('prescribed_coastal_level');
 if([c.rainfall,c.external,c.coastal].filter(Boolean).length>1)requested.add('combined_forcing');
 if(spec.forcing.outlets.length)requested.add('parameterised_outlets');
 const engines:Record<string,{capabilities:string[];execution:string}>=registry.engines;
 const unavailable:Record<string,string>=registry.unavailable;
 const engine=Object.hasOwn(engines,spec.engine)?engines[spec.engine]:undefined;
 const unsupported=[...requested].filter(c=>!engine?.capabilities.includes(c)).sort();
 const reasons=engine?[]:[Object.hasOwn(unavailable,spec.engine)?unavailable[spec.engine]:'Unknown engine; no fallback was selected.'];
 reasons.push(...unsupported.map(c=>'Unsupported capability: '+c));
 return {engine:spec.engine,compatible:reasons.length===0,required_capabilities:[...requested].sort(),unsupported_capabilities:unsupported,reasons,execution:engine?.execution??null,data_validation:'not_assessed',observed_accuracy:'unvalidated',
  limitations:['Capability compatibility does not verify terrain, datum alignment, solid-cell masks, source provenance or site accuracy.','No computation was started; executable arrays and identities require validation at dispatch.']};
}

export function assessDesignCapabilities(engineName:string,kinds:string[]){
 const engines:Record<string,{design_capabilities?:string[]}>=registry.engines,engine=engines[engineName],supported=new Set(engine?.design_capabilities??[]),unsupported=[...new Set(kinds)].filter(kind=>!supported.has(kind)).sort();
 return {engine:engineName,compatible:!!engine&&!unsupported.length,unsupported_designs:unsupported,reasons:engine?unsupported.map(kind=>'Unsupported design capability: '+kind):['Unknown or unavailable execution engine; no design fallback was selected.']};
}

/** Builds a metadata envelope; absent provenance stays explicitly unknown. */
export function scenarioSpec(input:GPUInput,forcing:ScenarioForcingV2,metadata:{engine?:string;bundleId?:string;horizontalCrs?:string;verticalDatum?:string;elevationOriginM?:number;inputHash?:string;requiredCapabilities?:string[]}={}):ScenarioSpecV2{
 const physicalStorm={duration:forcing.storm.duration,recession:forcing.storm.recession,depth:forcing.storm.depth,intervals:forcing.storm.intervals??null};
 return parseScenarioSpec({version:2,engine:metadata.engine??'webgl2-hll',domain:{nx:input.nx,ny:input.ny,dx_m:input.dx,dy_m:input.dy,horizontal_crs:metadata.horizontalCrs??'LOCAL_METRES',vertical_datum:metadata.verticalDatum??'unspecified',elevation_origin_m:metadata.elevationOriginM??null,bundle_id:metadata.bundleId??null},
  forcing:{...forcing,coastal:forcing.coastal??null,storm:physicalStorm},required_capabilities:metadata.requiredCapabilities??[],execution_input_hash:metadata.inputHash??null});
}
